---
title: "Results"
output:
  word_document: default
  always_allow_html: true
  html_document:
    self_contained: false
    keep_md: true
  pdf_document:
    fig_caption: yes
    includes:
      in_header: my_header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load myData, include=FALSE, echo=FALSE}
load("C:/Users/LPXJGB/Desktop/CHI-2020/CookingProject/fname.RData")
# required libraries
library(knitr)
library(kableExtra)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(htmlTable)
library(scales)
library(formattable)
library(magick)
library(flextable)
library(officer)
library(pander)
options(knitr.kable.NA = '')
```

An introduction to results. A description of each one of the results.

# Demographics and informative data


### Participants

```{r, warning=FALSE, echo=FALSE, message=FALSE}
p_df <- participants.list[, 1:9]

panderOptions('table.split.table', 300)
panderOptions('graph.fontsize', 8)
pander(p_df)
pandoc.footnote("your footnote here")
```