# load libraries and functions

# # ================ [1.0]install packages ================ 
# install.packages("xlsx")
# install.packages("tidyverse")
# install.packages("devtools")
# install.packages("janitor")
# install.packages("pivottabler")
# install.packages("plyr")
# install.packages("epiDisplay")
# install.packages("summarytools")
# install.packages("ggplot2")
# install.packages("hash")
# install.packages("dplyr")
# install.packages("rstudioapi")
# install.packages("ggthemes")
# install.packages("gridExtra")
# install.packages("reshape2")
# install.packages("viridis")
# install.packages("here")
# install.packages("gghighlight")
# install.packages("ggpubr")
# install.packages("multcomp")
# install.packages("carData")
# install.packages("qdap")
# install.packages("pracma")
# install.packages("treemap")
# install.packages("ArgumentCheck")
# install.packages("lubridate")
# install.packages("Rttf2pt1", dependencies = TRUE)
# install.packages("waffle", dependencies = TRUE)
# install.packages("hrbrthemes")
# install.packages("processx")
# install.packages("kableExtra")
# install.packages('rmarkdown')
# install.packages('tinytex')
# install.packages("readxl")
# install.packages("car")
# install.packages('knitr')
# install.packages('cgwtools')
# install.packages('gapminder')

# ================ [2.0] load libraries ================ 
library(devtools)
library(processx)
library(tidyverse)
library(readxl)
library(janitor)
library(pivottabler)
library(plyr)
library(epiDisplay)
library(summarytools)
library(hash)
library(dplyr)
library(rstudioapi)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(reshape2)
library(viridis)
library(here)
library(gghighlight)
library(ggpubr)
library(multcomp)
library(car)
library(treemap)
library(ArgumentCheck)
library(lubridate)
library(waffle)
library(magrittr)
library(hrbrthemes)
library(waffle)
library(Rttf2pt1)
library(magrittr)
library(rmarkdown)
library(kableExtra)
library(knitr)
library(tinytex)
library(cgwtools)
library(gapminder)

# hrbrthemes::import_roboto_condensed()
# devtools::install_github("hrbrmstr/waffle")
# devtools::install_github("svmiller/stevemisc")
# devtools::install_github("lbusett/insert_table")
# extrafont::loadfonts(device="win")
# tinytex::install_tinytex()  # install TinyTeX

# ================ [3.0]init functions ================ 
# mode function
getMode <- function(v){
  v <- v[!is.na(v)]
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

# ================ [4.0]global variables ================ 
# get unique items 
types <- c("c", "u", "e")
len.types <- length(types)

#set sessions 
sessions<- c("all", "reg", "new")
len.sessions <- length(sessions)